### PR TITLE
Updated wording for autoIndexId option (5914)

### PR DESCRIPTION
**Pull request by steveren**
@kay-kim RFM for `master`

My very first pull request!

### CODE REVIEW

**Comment by kay-kim** [comment]
Hey @steveren -- the commits include couple for the $indexStats change as well

**Comment by atsansone** [comment]
@kay-kim : I'm helping fix that.

**Comment by kay-kim** [comment]
Okay.  I think this is residual effect of not doing git checkout -b <newbranch> upstream/master   (everyone makes this mistake which means they accidentally make a branch of whatever local working branch they're on and picking up other commits).

cc: @atsansone @steveren 

In your .bashrc or .bash_profile, you can put

```
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
PS1="\w\$(parse_git_branch) $ "

```
so that if you're on a git branch, it'll tell you what branch you're on.

**Comment by atsansone** [comment]
@kay-kim : You have now explained why I use `zsh` and `oh-my-zsh`: http://ohmyz.sh/

**Comment by kay-kim** [comment]
merged!

**Pull request closed without merging**
