### PR TITLE
(DOCS-11711): Updated downgrade shutdown requirement.

### PR DESCRIPTION
**Pull request by atsansone**
@MongoCaleb : There are a few line wrap issues, but the big thing is the note that I added:

- [Standalone](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-standalone.html#restart-with-the-latest-oldversion-mongod-instance)
- [Replica Set](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-replica-set.html#downgrade-secondary-members-of-the-replica-set)
- [Sharded Cluster](https://docs-mongodbcom-staging.corp.mongodb.com/anthonysansone/DOCS-11711/release-notes/3.6-downgrade-sharded-cluster.html#downgrade-each-shard-one-at-a-time)

Staging build is still ongoing. Stage may not reflect code.

### CODE REVIEW

**Comment by atsansone** [comment]
@mbrinsmead : Review to you. Thanks!

**Comment by kevarh** [comment]
> errors result

I'd go with "errors may result". If it shuts down in under five minutes, you're OK.

One note that isn't important to include here is... Forcibly terminating mongod can cause `.count()` and `db.stats()` to be wrong as well as lengthen startup time on next boot (we have to run WT Recovery).

I can't see the entire context, do we call out `db.shutDownServer()` as the preferred choice in `<terminate-mongod-processes>`?

Other than that LGTM.

**Comment by atsansone** [comment]
@kay-kim : RFM for `master` and `v3.6`.

**Comment by mbrinsmead** [comment]
Reviewed changes mades for DOCS-11711.  LGTM -- this should meet out need.

**Pull request merged**
