### PR TITLE
Make cursor.map return value description clearer

### PR DESCRIPTION
**Pull request by valoricDe**

### CODE REVIEW

**Comment by valoricDe** [comment]
@milkie @kay-kim I signed the Contributor Agreement (ID: CBJCHBCAABAAZjIuGNC1zTW0wv90McWvV0pR8mIWgnMB)

Between the links to Style Guide, Build etc are not working on https://github.com/mongodb/docs/blob/master/CONTRIBUTING.rst

**Comment by kay-kim** [comment]
Hi @valoricDe --
Thank you so much for the pull request as well as signing the Contributor Agreement.

Currently, the manual page  refers to the mongo shell.  To see the function definition for the mongo shell, you can omit the parenthesis for the function in the mongo shell:

`db.users.find().map`

Typing the above in the mongo shell should return something like
````
function(func) {
    var a = [];
    while (this.hasNext())
        a.push(func(this.next()));
    return a;
}
````

As such, I will close this pull request.  However, we very much appreciate your generosity with your time and efforts to help us improve the docs.

Regards,

Kay Kim

**Comment by kay-kim** [comment]
@valoricDe  -- Just realized that you might want to update the pull request to something else (I haven't had coffee yet so brain hasn't kicked started yet).  If so, give a holler and will reopen.

**Comment by valoricDe** [comment]
Oh, thanks to you I realised that I should have used the nodejs reference documentation, so https://mongodb.github.io/node-mongodb-native/2.2/api/Cursor.html#map

**Comment by kay-kim** [comment]
Great.  As an fyi -- the node.js driver landing page https://mongodb.github.io/node-mongodb-native/
has links to other versions.

**Pull request closed without merging**
