### PR TITLE
add SPM Performance Monitoring

### PR DESCRIPTION
**Pull request by megastef**
for more info see: 
- [spm-agent-mongodb Github repository](https://github.com/sematext/spm-agent-mongodb)
- [SPM Performance Monitoring - MongoDB integrations page](https://sematext.com/spm/integrations/mongodb-monitoring/)

---
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/2573)

### CODE REVIEW

**Comment by megastef** [comment]
When could this be merged?

**Comment by megastef** [comment]
Ping! Why is this PR still not merged? Do we need to change something?

**Comment by otisg** [comment]
+1 for merging this in.  It's the docs and doesn't break anything.

**Comment by otisg** [comment]
Is there any way we can get this merged?  It's just documentation.

**Comment by kay-kim** [comment]
Hi.  Apologies for the significant delay in response.   To merge this, could you sign the Contributor Agreement found at https://www.mongodb.com/legal/contributor-agreement

Note also that you can also add your project to https://www.mongodb.com/contact/production-deployment-application

**Comment by megastef** [comment]
Thanks @kay-kim for the support. I signed the contributor agreement.

**Comment by kay-kim** [comment]
Merged!  Thanks again for your patience. This should be published sometime tomorrow.

**Comment by otisg** [comment]
@kay-kim - thanks!  Do you know if that is supposed to be published under https://docs.mongodb.com/v3.2/administration/monitoring/ ?  I'm asking because you said it should be published the next day, but it's been 5-6 days now.  Maybe that page is not being rebuilt or republished?  Or maybe I'm looking at the wrong page/version?  Thanks.

**Comment by kay-kim** [comment]
You should see it on https://docs.mongodb.com/master/administration/monitoring/

**Comment by otisg** [comment]
Thanks, see it!

**Pull request closed without merging**
