### PR TITLE
(DOCS-10248): Fixed command prompt listings.

### PR DESCRIPTION
**Pull request by atsansone**
@kay-kim : This builds on the DOCS-11026 already in RFM. RFM for `v3.6` and `master`.

---
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/3329)

### CODE REVIEW

**Comment by kay-kim** [comment]
@atsansone  -- have 3 commits instead of 1 -- why is that.

please review https://wiki.corp.mongodb.com/pages/viewpage.action?pageId=87459398  
people have found this page useful

**Comment by atsansone** [comment]
@kay-kim : I'm having difficulties with the branching from branches as we discussed to keep the changes atomic / ticketed. I'll fix this and keep exploring.

**Comment by atsansone** [comment]
@kay-kim : This may exist until the prior branch is merged.

**Comment by atsansone** [comment]
@kay-kim : Going to work on this branching issue with @nlarew .

**Comment by kay-kim** [comment]
Just an FYI -- because this pull had the same commits as
https://github.com/mongodb/docs/pull/3329  (which was merged, this pull is effectively closed -- but leaving in place if you want to look at it).

**Pull request merged**
