### PR TITLE
Testing - DO NOT MERGE - Docsp 5628 scts

### PR DESCRIPTION
**Pull request by gilberto-mdb**

### CODE REVIEW

**Comment by kay-kim** [comment]
Hey @gilberto-mdb  -- did you mean to do this pull request that adds  pages that will render as ... -sct into the 4.2 manual and will conflict with the aggregate/find/replSetReconfig pages in seo/google indexing.

More importantly, I believe new content has not been technically vetted.  If I'm remembering correctly, various new content were added without validation only  for the purposes of template review.

**Comment by gilberto-mdb** [comment]
I did not mean to do that! Sue and I were testing out the staging builder.
Sorry about that! I’ll close the PR.

**Comment by kay-kim** [comment]
👍  It's okay to try testing the staging builder with the pull requests - but to ensure that we don't accidentally merge, if we could just edit the pull request text to say -- For testing only or something.

**Comment by gilberto-mdb** [comment]
@kay-kim Updated the title - thanks Kay.

**Comment by kay-kim** [comment]
closing as sue has already committed the worker.sh for us and we've set up the webhook for our forks of the repo.

**Pull request closed without merging**
