### PR TITLE
Correct note on deprecation

### PR DESCRIPTION
**Pull request by asya999**
Ensure index is not an alias for create index

### CODE REVIEW

**Comment by p-mongo** [comment]
On 4.4 ensureIndex is defined as follows:

```
MongoDB Enterprise ruby-driver-rs:PRIMARY> db.c.ensureIndex
function(keys, options) {
    var result = this.createIndex(keys, options);

    if (this.getMongo().writeMode() != "legacy") {
        return result;
    }

    err = this.getDB().getLastErrorObj();
    if (err.err) {
        return err;
    }
    // nothing returned on success
}
```

Seems like it just calls createIndex?

**Comment by asya999** [comment]
It doesn’t pass all the options at least in 4.2

We are removing it in the next version anyway.

**Comment by p-mongo** [comment]
4.2.8 shell shows:

```
MongoDB Enterprise mongos> db.x.ensureIndex
function(keys, options) {
    var result = this.createIndex(keys, options);

    if (this.getMongo().writeMode() != "legacy") {
        return result;
    }

    err = this.getDB().getLastErrorObj();
    if (err.err) {
        return err;
    }
    // nothing returned on success
}
```

**Comment by asya999** [comment]
@p calling createIndex with three parameters has SIGNIFICANTLY different effect than calling ensureIndex with three parameters.   Alias implies the same effect.

**Comment by p-mongo** [comment]
I see, that makes sense.

**Review by p-mongo — APPROVED** [review]

**Comment by andf-mongodb** [comment]
Thank you! Merged & will backport.

**Pull request merged**
