### PR TITLE
DOCSP-1457 - Integrating compass into query null fields page

### PR DESCRIPTION
**Pull request by jeff-allen-mongo**
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/jeffreyallen/DOCSP-1457/tutorial/query-for-null-fields.html

---
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/3140)

### CODE REVIEW

**Comment by jeff-allen-mongo** [comment]
Please hold off on merging until we've integrated Compass into all CRUD pages.

**Comment by jeff-allen-mongo** [comment]
RFM!

**Comment by kay-kim** [comment]
merged!

**Comment by kay-kim** [comment]
https://github.com/mongodb/docs/commit/a2539916c77b8816d36b01a903512a04936098de

**Pull request closed without merging**
