### PR TITLE
DOCS-10737: server parameter honorSystemUmask

### PR DESCRIPTION
**Pull request by steveren**
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/3021)

### CODE REVIEW

**Comment by steveren** [comment]
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/steverenaker/DOCS-10737/release-notes/3.6.html#mongod-options

For the release notes, I created a new section for new mongod options (since there are many in 3.6) and used the same formatting as currently exists for the new Sessions parameters. If it would be better to make a table with the option name on the left and a description on the right, let me know and I'll make it so.

**Comment by kay-kim** [comment]
Ah -- this would for the present just go under the general enhancements.
We tend to subsection the key features -- sessions/(we'll have change streams)/agg ...
But for new options for mongod, if the new options are specific to some feature, then we'll group those instead of a section on new mongod options since some new options for mongod could be available in mongos and mongo shell.  Close to when we have the bulk of things doc'ed, I think your sectioning probably is the way to go so that we list the options in couple of places on that page. But for now, could we just add a single bullet point under the general enhancements?  That way, we can control when we do the reorging (vs. someone opening a ticket now going 'Hey, you haven't listed some of the new options under that section').

**Comment by steveren** [comment]
Thanks Kay. Updated as you suggested.

**Comment by kay-kim** [comment]
merged!  Thanks Steve.

**Pull request closed without merging**
