### PR TITLE
DOCS-8086: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by i80and**
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/2645)

### CODE REVIEW

**Comment by i80and** [comment]
Please hold off on merging at the moment; these changes are fine, but the Ubuntu 16.04 packages are quirky.

**Comment by kay-kim** [comment]
Should this just go away?

**Comment by i80and** [comment]
Nope; just waiting until the 3.2.8 packages are released.

**Comment by i80and** [comment]
Merged.

**Pull request closed without merging**
