### PR TITLE
DOCS-6796, DOCS-7621, DOCS-7626: administration reorg

### PR DESCRIPTION
**Pull request by schmalliso**
This change is [Reviewable](https://reviewable.io/reviews/mongodb/docs/2670)

### CODE REVIEW

**Comment by schmalliso** [comment]
I need to add the redirects, so do not merge yet!

**Comment by schmalliso** [comment]
Have you put in redirects for these?
* removed: source/administration/backup.txt
* added: source/administration/configuration-and-maintenance.txt
* removed: source/administration/data-management.txt
* removed: source/administration/maintenance.txt
* removed: source/administration/optimization.txt
* removed: source/administration/production-checklist.txt
* removed: source/administration/strategy.txt
* removed: source/administration/tutorials.txt
* removed: source/applications/design-notes.txt
* removed: source/core/administration.txt
* removed: source/reference/administration.txt
* removed: source/tutorial/admin-manage-journaling.txt
* removed: source/tutorial/backup-small-sharded-cluster-with-mongodump.txt
* removed: source/tutorial/restore-single-shard.txt

**Comment by schmalliso** [comment]
Redirects added! Should be good to go =D

**Comment by kay-kim** [comment]
merged!

**Pull request closed without merging**
